// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoUwr5q0QyYnjCUstDKSPhbFH70LljIeA',
    appId: '1:148341878787:web:4066ee392e72bd40a41e36',
    messagingSenderId: '148341878787',
    projectId: 'login-work-ffce1',
    authDomain: 'login-work-ffce1.firebaseapp.com',
    storageBucket: 'login-work-ffce1.firebasestorage.app',
    measurementId: 'G-493WJ2P0TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvpR7zyuTpXkXKvtiqHgJ-MrJcdD9AVw',
    appId: '1:148341878787:android:db5f44b718ed336aa41e36',
    messagingSenderId: '148341878787',
    projectId: 'login-work-ffce1',
    storageBucket: 'login-work-ffce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCf9-Sx915bB44JhxQWSXP92wlFYwDWo',
    appId: '1:148341878787:ios:0181e55f97b97e58a41e36',
    messagingSenderId: '148341878787',
    projectId: 'login-work-ffce1',
    storageBucket: 'login-work-ffce1.firebasestorage.app',
    iosBundleId: 'com.example.loginAuth',
  );
}
